# Specify the parent image from which we build
FROM node:18.9.0-alpine3.16

ENV NODE_ENV=development

# Set the working directory
RUN mkdir -p /usr/src/welcome_bot
WORKDIR /usr/src/welcome_bot

# Install app dependencies
COPY package*.json ./

RUN npm install
RUN npm install -g nodemon
COPY . .

# Run the application
CMD [ "npm", "run", "start.dev" ]